name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
    name: python-${{ matrix.python }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup python-${{ matrix.python }}
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Lint (pylint)
        run: pylint *.py
      - name: Lint (ruff)
        run: ruff check --output-format=github .

  formatting:
    name: formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: Setup
        run: pip install -r requirements.txt
      - name: Check Formatting
        run: ruff format --check --diff .
