name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.7", "3.8", "3.9", "3.10" ]
    name: python-${{ matrix.python }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup python-${{ matrix.python }}
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Test
        run: pylint *.py
